### ISSUE TITLE
Train model

### ISSUE THREAD

**Issue by hadartourgeman** [grip-unina/PoIForensics-Audio#1]
Hi:)
I would like to ask, how can I train the model? 
I saw there is only a trained one in your git.

And also, if I want to predict if an audio is real or fake, when the poi in included in the training set- how can I do it?
I saw in your README file, that you mentioned how to extract the codes to the csv file- what threshold did you use?
Thanks a lot!

**Comment by Wertiz** [comment]
> how can I train the model?
> I saw there is only a trained one in your git.

There are two trained model in the repository (one with augmentation and one without) but there is no code to train the model at the moment. However, to predict any audio there is no need to retrain the network.

> I want to predict if an audio is real or fake, when the poi in included in the training set- how can I do it?

Once you have executed the whole pipeline, you will have a csv with a score for each test file. To perform final classification you can use that score.

> what threshold did you use?

We did not use a universal threshold as it is quite a complicated matter to find a single value that works across all datasets. In our experiment we computed thresholds for each dataset by meaning of the AUC for various threshold.

In case you are in the position where you have the reference set for a POI and a single file you want to verify, I would suggest that you collect additional real audios that you put only in test. This way, you can check the distance of the file you want to verify next to the real ones and see how much further it is distance-wise.
